name: Deploy to GitHub Pages

# Trigger on push to main branch (adjust if you use a different branch)
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write       # allow publishing to GitHub Pages
      id-token: write    # required by configure-pages

    steps:
      # 1) Check out your repository
      - uses: actions/checkout@v4

      # 2) (Optional) build your site or export your game here
      # - name: Build site
      #   run: |
      #     npm ci
      #     npm run build
      #   # or your Godot HTML5 export steps

      # 3) Configure the Pages environment
      - uses: actions/configure-pages@v3

      # 4) Upload the directory you want to publish (e.g. './docs' or './public' or './export')
      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./docs

      # 5) Deploy to GitHub Pages
      - uses: actions/deploy-page
